### ISSUE TITLE
Current release (0.2.5) of the bioformats2raw conda package fails on Windows

### ISSUE THREAD

**Issue by manics** [ome/conda-bioformats2raw#3]
```
conda create -n bf -c ome bioformats2raw
conda activate bf
```
```
(bf) C:\Users\vagrant\Documents>bioformats2raw --version
Version = 0.2.5
Bio-Formats version = 6.4.0

(bf) C:\Users\vagrant\Documents>conda list
# packages in environment at C:\ProgramData\Miniconda3\envs\bf:
#
# Name                    Version                   Build  Channel
bioformats2raw            0.2.5                         0    ome
blosc                     1.20.1               h7bd577a_0
lz4-c                     1.9.2                hf4a77e7_3
openjdk                   11.0.6               he774522_1
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
xz                        5.2.5                h62dcd97_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.5                h04227a9_0

(bf) C:\Users\vagrant\Documents>bioformats2raw test.fake out
2020-10-27 10:27:20,890 [main] INFO  loci.formats.ImageReader - FakeReader initializing test.fake
2020-10-27 10:27:21,156 [main] INFO  c.g.bioformats2raw.Converter - Using 2 pyramid resolutions
2020-10-27 10:27:21,156 [main] INFO  c.g.bioformats2raw.Converter - Preparing to write pyramid sizeX 512 (tileWidth: 102
4) sizeY 512 (tileWidth: 1024) imageCount 1
2020-10-27 10:27:21,171 [main] ERROR c.g.bioformats2raw.Converter - Error while writing series 0
java.lang.UnsatisfiedLinkError: C:\Users\vagrant\AppData\Local\Temp\1\jna-226895185\jna17348274492475311593.dll: Can't f
ind dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[na:na]
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[na:na]
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[na:na]
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[na:na]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617) ~[na:na]
        at java.base/java.lang.Runtime.load0(Runtime.java:767) ~[na:na]
        at java.base/java.lang.System.load(System.java:1834) ~[na:na]
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at com.sun.jna.Native.<clinit>(Native.java:140) ~[jna-4.2.2.jar:4.2.2 (b0)]
        at org.blosc.IBloscDll.<clinit>(IBloscDll.java:15) ~[jblosc-1.0.1.jar:na]
        at org.blosc.JBlosc.init(JBlosc.java:30) ~[jblosc-1.0.1.jar:na]
        at org.blosc.JBlosc.<init>(JBlosc.java:24) ~[jblosc-1.0.1.jar:na]
        at org.janelia.saalfeldlab.n5.blosc.BloscCompression.<clinit>(BloscCompression.java:70) ~[n5-blosc-1.1.0.jar:1.1
.0]
        at com.glencoesoftware.bioformats2raw.Converter$N5Compression.getCompressor(Converter.java:143) ~[bioformats2raw
-0.2.5.jar:0.2.5]
        at com.glencoesoftware.bioformats2raw.Converter$N5Compression.access$100(Converter.java:134) ~[bioformats2raw-0.
2.5.jar:0.2.5]
        at com.glencoesoftware.bioformats2raw.Converter.saveResolutions(Converter.java:899) ~[bioformats2raw-0.2.5.jar:0
.2.5]
        at com.glencoesoftware.bioformats2raw.Converter.write(Converter.java:549) ~[bioformats2raw-0.2.5.jar:0.2.5]
        at com.glencoesoftware.bioformats2raw.Converter.convert(Converter.java:508) ~[bioformats2raw-0.2.5.jar:0.2.5]
        at com.glencoesoftware.bioformats2raw.Converter.call(Converter.java:384) ~[bioformats2raw-0.2.5.jar:0.2.5]
        at com.glencoesoftware.bioformats2raw.Converter.call(Converter.java:93) ~[bioformats2raw-0.2.5.jar:0.2.5]
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783) ~[picocli-4.2.0.jar:4.2.0]
        at picocli.CommandLine.access$900(CommandLine.java:145) ~[picocli-4.2.0.jar:4.2.0]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150) ~[picocli-
4.2.0.jar:4.2.0]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144) ~[picocli-4.2.0.jar:4.2.0]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108) ~[picocli-4.2.0.jar:4.2.0]
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968) ~[picocli-4.2.0.jar:4
.2.0]
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2349) ~[picocli-4.2.0.jar:4.2.0]
        at picocli.CommandLine.parseWithHandler(CommandLine.java:2284) ~[picocli-4.2.0.jar:4.2.0]
        at picocli.CommandLine.call(CommandLine.java:2560) ~[picocli-4.2.0.jar:4.2.0]
        at com.glencoesoftware.bioformats2raw.Converter.main(Converter.java:1110) ~[bioformats2raw-0.2.5.jar:0.2.5]
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.glencoesoftware.biof
ormats2raw.Converter@4f2b503c): java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: C:\Users\vagrant\AppData\Loc
al\Temp\1\jna-226895185\jna17348274492475311593.dll: Can't find dependent libraries
        at picocli.CommandLine.executeUserObject(CommandLine.java:1792)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1968)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2349)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:2284)
        at picocli.CommandLine.call(CommandLine.java:2560)
        at com.glencoesoftware.bioformats2raw.Converter.main(Converter.java:1110)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: C:\Users\vagrant\AppData\Local\Temp\1\jna-2268951
85\jna17348274492475311593.dll: Can't find dependent libraries
        at com.glencoesoftware.bioformats2raw.Converter.unwrapException(Converter.java:1052)
        at com.glencoesoftware.bioformats2raw.Converter.convert(Converter.java:512)
        at com.glencoesoftware.bioformats2raw.Converter.call(Converter.java:384)
        at com.glencoesoftware.bioformats2raw.Converter.call(Converter.java:93)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        ... 9 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\vagrant\AppData\Local\Temp\1\jna-226895185\jna17348274492475311593.d
ll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1834)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
        at com.sun.jna.Native.<clinit>(Native.java:140)
        at org.blosc.IBloscDll.<clinit>(IBloscDll.java:15)
        at org.blosc.JBlosc.init(JBlosc.java:30)
        at org.blosc.JBlosc.<init>(JBlosc.java:24)
        at org.janelia.saalfeldlab.n5.blosc.BloscCompression.<clinit>(BloscCompression.java:70)
        at com.glencoesoftware.bioformats2raw.Converter$N5Compression.getCompressor(Converter.java:143)
        at com.glencoesoftware.bioformats2raw.Converter$N5Compression.access$100(Converter.java:134)
        at com.glencoesoftware.bioformats2raw.Converter.saveResolutions(Converter.java:899)
        at com.glencoesoftware.bioformats2raw.Converter.write(Converter.java:549)
        at com.glencoesoftware.bioformats2raw.Converter.convert(Converter.java:508)
        ... 12 more

(bf) C:\Users\vagrant\Documents>
```

**Comment by manics** [comment]
Installing `openjdk=8` on Windows fixes this problem, however `openjdk=11` works fine on OS X.

**Comment by jburel** [comment]
It now works with java 11 in https://github.com/ome/conda-bioformats2raw/pull/4
see https://github.com/jburel/conda-bioformats2raw/actions/runs/592806657
